---
type: aws-security-group-ingress
version: 0.2.0
core: 0.2.x

description: "My component description"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  description:
    type: string
    displayName: Ingress rule desription
    description: Ingress rule desription
    example: Ingress rule for accessing ephemeral port range
  ipPermissions:
    type: array
    displayName: Ingress rules
    description: Ingress rules
    required: true
    example:
      - fromPort: 8080
        ipProtocol: tcp
        ipRanges:
          - cidrIp: 10.0.0.0/16
            description: ipv4 description
        ipv6Ranges:
          - cidrIpv6: '2600:1f18:24c2:b200::/56'
            description: ipv6cidr description'
        prefixListIds:
          - description: 'STRING_VALUE'
            prefixListId: 'STRING_VALUE'
        toPort: 8080

outputTypes:
  myOutput:
    type: string
    description: my output string
